# Generated by Django 5.2.1 on 2025-05-26 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=500)),
                ('price', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=500)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('furniture_type', models.CharField(max_length=100)),
                ('furniture_style', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Item',
                'verbose_name_plural': 'Favorite Items',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'link')},
            },
        ),
    ]
